rootLogger.level = WARN
rootLogger.appenderRef.console.ref = Console

# FIX: Changed ID from 'ge.thesis' to 'myApp'
logger.myApp.name = ge.thesis
logger.myApp.level = INFO
logger.myApp.appenderRef.console.ref = Console

# FIX: Changed ID from 'org.apache.flink' to 'flink'
logger.flink.name = org.apache.flink
logger.flink.level = WARN

# FIX: Changed ID from 'org.apache.kafka' to 'kafka'
logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n